services:
  postgres:
    container_name: postgres
    image: postgres:17.4
    environment:
      POSTGRES_USER: hugo
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: healthApi
    ports:
      - "5432:5432"
    networks:
      - health

  redis:
    container_name: redis
    image: redis:7.4.2-alpine
    ports:
      - "6379:6379"
    networks:
      - health

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - health

networks:
  health:
    driver: bridge
